upload:
  chunkSize: 50
  thread:
    maxSize: 25
  queue:
    maxSize: 100
    dir: "C:\\Users\\NineSun\\Desktop\\11\\"
  root:
    dir: "C:\\Users\\26490\\Desktop\\11"
  window:
    root: ""

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
  servlet:
    multipart:
      max-file-size: 6MB
      max-request-size: 10GB